// Our labels along the x-axis
Chart.defaults.global.defaultFontColor = "#000";

var LGA = [
  "Aniocha North",
  "Aniocha South",
  "Bomadi",
  "Burutu",
  "Ethiope East",
  "Ethiope West",
  "Ika NorthEast",
  "Ika South",
  "Isoko North",
  "Isoko South",
  "Ndokwa East",
  "Ndokwa West",
  "Okpe",
  "Oshimili North",
  "Oshimili South",
  "Patani",
  "Sapele",
  "Udu",
  "Ughelli North",
  "Ughelli South",
  "Ukwuani",
  "Uvwie",
  "Warri North",
  "Warri South",
  "Warri SouthWest",
];
//line
var ctxL = document.getElementById("lineChart").getContext("2d");
var myLineChart = new Chart(ctxL, {
  type: "bar",
  data: {
    labels: LGA,
    datasets: [
      {
        label: "TESTING PERFORMANCE BAROMETER",
        data: [
          1.0,
          2.3,
          1.7,
          0.0,
          2.5,
          9.3,
          2.7,
          4.6,
          0.7,
          2.0,
          0.6,
          5.5,
          7.1,
          28.5,
          88.1,
          0.3,
          14.1,
          9.0,
          7.6,
          1.6,
          1.3,
          16.7,
          0.3,
          11.8,
          0.2,
          9.0,
        ],
        backgroundColor: [
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
          "#d21910",
        ],
      },
    ],
  },
  options: {
    responsive: true,
    maintainAspectRatio: false,
  },
});
